from collections import Counter
from datetime import datetime

def get_mood_counts(history):
    return Counter(history)


def get_session_summary(history, feedback):
    most_common_mood = Counter(history).most_common(1)[0][0]
    negative_feedback = feedback.count("No")

    return most_common_mood, negative_feedback


def therapy_session_insight(distress_levels, calm_levels):
    if not distress_levels or not calm_levels:
        return "Insufficient data for therapeutic insight."

    avg_distress = sum(distress_levels) / len(distress_levels)
    avg_calm = sum(calm_levels) / len(calm_levels)

    if avg_calm > avg_distress:
        return "Music recommendations showed a positive calming effect during the session."
    else:
        return "Emotional response varied; further personalization may improve outcomes."


def generate_session_report(
    mode,
    mood_history,
    feedback_list,
    detailed_feedback,
    therapy_insight=None
):
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    report = []
    report.append("MoodMusicAI – Session Report")
    report.append("=" * 35)
    report.append(f"Session Time: {timestamp}")
    report.append(f"Usage Mode: {mode}")
    report.append("")

    # Mood history
    report.append("Mood History:")
    if mood_history:
        report.append(", ".join(mood_history))
    else:
        report.append("No mood data recorded.")
    report.append("")

    # Feedback summary
    report.append("Feedback Summary:")
    if feedback_list:
        yes_count = feedback_list.count("Yes")
        no_count = feedback_list.count("No")
        report.append(f"Positive matches: {yes_count}")
        report.append(f"Negative matches: {no_count}")
    else:
        report.append("No feedback recorded.")
    report.append("")

    # Detailed feedback
    report.append("Detailed Feedback Entries:")
    if detailed_feedback:
        for i, fb in enumerate(detailed_feedback, start=1):
            report.append(
                f"{i}. Mood Match: {fb['mood_match']}, "
                f"Emotion Shift: {fb['emotional_shift']}, "
                f"Coping Effectiveness: {fb['coping_effectiveness']}, "
                f"Comfort Level: {fb['comfort_level']}"
            )
    else:
        report.append("No detailed feedback entries.")
    report.append("")

    # Therapy insight
    if therapy_insight:
        report.append("Therapeutic Insight:")
        report.append(therapy_insight)
        report.append("")

    report.append(
        "Disclaimer: This report is generated by a prototype system. "
        "It is not a medical diagnosis and should not be used for clinical decisions."
    )

    return "\n".join(report)
